version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    labels:
      - type:enhancement
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - type:enhancement
