version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: 0 12 * * *
    reviewers:
      - akkinoc
    assignees:
      - akkinoc
    labels:
      - type:dependencies
    milestone: 5
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: cron
      cronjob: 0 12 * * *
    reviewers:
      - akkinoc
    assignees:
      - akkinoc
    labels:
      - type:dependencies
    milestone: 5
