source "https://rubygems.org"
gem "classifier-reborn", "~> 2.3"
gem "jekyll", "~> 4.4"
gem "minimal-mistakes-jekyll", "~> 4.27"
gem "numo-linalg", "~> 0.1"
gem "numo-narray", "~> 0.9"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-include-cache", "~> 0.2"
  gem "jekyll-last-modified-at", "~> 1.3"
  gem "jekyll-minifier", "~> 0.2"
  gem "jekyll-paginate", "~> 1.1"
  gem "jekyll-sass-converter", "~> 2.2"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-target-blank", "~> 2.0"
  gem "jemoji", "~> 0.13"
end
