name: build
on: [push, pull_request]
env:
  TZ: Asia/Tokyo
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.82.0
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Build the site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Deploy the site
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: akkinoc.dev
