name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: macos-15
    env:
      TZ: Asia/Tokyo
      JEKYLL_ENV: production
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0 # for jekyll-last-modified-at
      - name: Install Homebrew packages
        run: brew bundle --file .Brewfile
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.263.0
        with:
          bundler-cache: true
      - name: Build the site
        run: bundle exec jekyll build
