name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  TZ: Asia/Tokyo
jobs:
  build:
    name: Build
    runs-on: macos-15
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # for jekyll-last-modified-at
      - name: Install Homebrew Packages
        run: brew install lapack openblas # for classifier-reborn
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.244.0
        with:
          bundler-cache: true
      - name: Build the site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Deploy the site
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: akkinoc.dev
        if: ${{ github.ref == 'refs/heads/main' }}
